on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  build_and_test:
    name: build
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test